name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release-signing:
    runs-on: ubuntu-latest
    steps:
      - name: signing
        run: |
          echo "RELEASE!"
          echo "12345abcdef" > release.sig
    

