name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release-docker:
    permisisons:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/test.yml
    secrets: inherit
  release-signing:
    runs-on: ubuntu-latest
    steps:
      - name: signing
        run: |
          echo "RELEASE!"
          echo "12345abcdef" > release.sig
    

