name: Renovate
on:
  schedule:
    - cron: '0/1 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate Renovate JSON
        run: jq type .github/renovate.json
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.1.6
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
